#Prefixes des routes de l'application

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

rb_parcours:
    resource: "@RBParcoursBundle/Resources/config/routing.yml"
    prefix:   /parcours

rb_ecrit:
    resource: "@RBEcritBundle/Resources/config/routing.yml"
    prefix:   /ecrit

rb_biographie:
    resource: "@RBBiographieBundle/Resources/config/routing.yml"
    prefix:   /biographie

rb_contact:
    resource: "@RBContactBundle/Resources/config/routing.yml"
    prefix:   /contact

#Authentification

login:
    path:     /login
    defaults: { _controller: RBUserBundle:Security:login }

login_check:
    path:     /login_check
    
logout:
    path:     /logout