# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        RB\UserBundle\Entity\User: sha512


#role_hierarchy vide car un seul Role

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:  RBUserBundle:User
                property: username

    provider:              main
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:       ^/(_(profiler|wdt)|css|images|js)/
            security:      false

        main:
            pattern:        ^/
            anonymous:      true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
