<?php

namespace RB\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  /*
   * Crypte un mot de passe avec l'encodage sha12  
   */
  public function crypto($password)
  {

    $salt='sha12';
    $iterations=5000;
    $salted = $password.'{'.$salt.'}';
    $digest = hash('sha512', $salted, true);

    for ($i = 1; $i < $iterations; $i++) {
        $digest = hash('sha512', $digest.$salted, true);
    }

    $cryptedPass = base64_encode($digest);

    return $cryptedPass;
   
  }

}
