<?php

namespace RB\ParcoursBundle\Repository;

/**
 * SousPartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousPartieRepository extends \Doctrine\ORM\EntityRepository
{
}
