RB_parcours_home:
    path:     /
    defaults: { _controller: RBParcoursBundle:Parcours:index }

RB_parcours_vue_periode:
    path:     /periode/{id}
    defaults: { _controller: RBParcoursBundle:Parcours:vuePeriode }
    requirements:
        id: \d+

RB_parcours_vue_oeuvre:
    path:     /periode/oeuvre/{id}
    defaults: { _controller: RBParcoursBundle:Parcours:vueOeuvre }
    requirements:
        id: \d+