RB_parcours_home:
    path:     /
    defaults: { _controller: RBParcoursBundle:Parcours:index }

RB_parcours_vue_periode:
    path:     /periode/{id}
    defaults: { _controller: RBParcoursBundle:Parcours:vuePeriode }
    requirements:
        id: \d+