RB_parcours_home:
    path:     /
    defaults: { _controller: RBParcoursBundle:Parcours:index }

RB_parcours_vue_periode:
    path:     /vue_periode
    defaults: { _controller: RBParcoursBundle:Parcours:vuePeriode }